# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "EditorConfig"

on:
    pull_request: null
    push:
        branches:
        - "main"
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    editorconfig:
        name: "Lint"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Check EditorConfig configuration"
            run: "test -f .editorconfig"
        -
            name: "Check adherence to EditorConfig"
            uses: "greut/eclint-action@v0"
        -
            name: "Look for TAB characters in the middle of the line"
            run: |
                ! git grep --perl-regexp --line-number -I '^(?!//)[^\t]+\t'
